name       : perl-super
version    : '1.20190531'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/C/CH/CHROMATIC/SUPER-1.20190531.tar.gz : 685d1ee76e7f0e9006942923bf7df8b11c107132992917593dcf7397d417d39a
homepage   : https://metacpan.org/pod/SUPER
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : SUPER - control superclass method dispatch
description: |
    SUPER - control superclass method dispatch
builddeps  :
    - perl-module-build
    - perl-sub-identify
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
