name       : perl-super
version    : 1.20141117
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/C/CH/CHROMATIC/SUPER-1.20141117.tar.gz : 1a620e7d60aee9b13b1b26a44694c43fdb2bba1755cfff435dae83c7d42cc0b2
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : SUPER - control superclass method dispatch
description: |
    SUPER - control superclass method dispatch
builddeps  :
    - perl-module-build
    - perl-sub-identify
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
